# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'objectexplorer_ui.ui'
#
# Created: Fri Nov 29 21:01:28 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ObjectExplorer(object):
    def setupUi(self, ObjectExplorer):
        ObjectExplorer.setObjectName("ObjectExplorer")
        ObjectExplorer.resize(422, 677)
        self.centralwidget = QtGui.QWidget(ObjectExplorer)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.spinBox_depth = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_depth.setProperty("value", 2)
        self.spinBox_depth.setObjectName("spinBox_depth")
        self.gridLayout.addWidget(self.spinBox_depth, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 3, 1, 1)
        self.spinBox_length = QtGui.QSpinBox(self.centralwidget)
        self.spinBox_length.setProperty("value", 20)
        self.spinBox_length.setObjectName("spinBox_length")
        self.gridLayout.addWidget(self.spinBox_length, 1, 4, 1, 1)
        self.checkBox_expandAll = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_expandAll.setObjectName("checkBox_expandAll")
        self.gridLayout.addWidget(self.checkBox_expandAll, 1, 5, 1, 1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 6, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(371, 41))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox_mapping = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_mapping.setGeometry(QtCore.QRect(90, 20, 61, 17))
        self.checkBox_mapping.setChecked(True)
        self.checkBox_mapping.setObjectName("checkBox_mapping")
        self.checkBox_sequence = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_sequence.setGeometry(QtCore.QRect(10, 20, 70, 17))
        self.checkBox_sequence.setChecked(True)
        self.checkBox_sequence.setObjectName("checkBox_sequence")
        self.checkBox_moduleobject = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_moduleobject.setGeometry(QtCore.QRect(250, 20, 91, 17))
        self.checkBox_moduleobject.setObjectName("checkBox_moduleobject")
        self.checkBox_mainobject = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_mainobject.setGeometry(QtCore.QRect(160, 20, 81, 17))
        self.checkBox_mainobject.setChecked(True)
        self.checkBox_mainobject.setObjectName("checkBox_mainobject")
        self.checkBox_other = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_other.setGeometry(QtCore.QRect(350, 20, 51, 17))
        self.checkBox_other.setObjectName("checkBox_other")
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 7)
        self.treeWidget = QtGui.QTreeWidget(self.centralwidget)
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeWidget.setAnimated(True)
        self.treeWidget.setObjectName("treeWidget")
        self.gridLayout.addWidget(self.treeWidget, 3, 0, 1, 7)
        self.lineEdit_rootObject = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_rootObject.setObjectName("lineEdit_rootObject")
        self.gridLayout.addWidget(self.lineEdit_rootObject, 0, 1, 1, 4)
        ObjectExplorer.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ObjectExplorer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 422, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        ObjectExplorer.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ObjectExplorer)
        self.statusbar.setObjectName("statusbar")
        ObjectExplorer.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(ObjectExplorer)
        self.actionExit.setObjectName("actionExit")
        self.actionCopy_path = QtGui.QAction(ObjectExplorer)
        self.actionCopy_path.setObjectName("actionCopy_path")
        self.menuFile.addAction(self.actionCopy_path)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ObjectExplorer)
        QtCore.QMetaObject.connectSlotsByName(ObjectExplorer)

    def retranslateUi(self, ObjectExplorer):
        ObjectExplorer.setWindowTitle(QtGui.QApplication.translate("ObjectExplorer", "ObjectExplorer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ObjectExplorer", "Root:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ObjectExplorer", "Max depth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ObjectExplorer", "Max length:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_expandAll.setText(QtGui.QApplication.translate("ObjectExplorer", "Expand all", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("ObjectExplorer", "Update tree", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("ObjectExplorer", "Show item categories:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_mapping.setText(QtGui.QApplication.translate("ObjectExplorer", "mapping", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_sequence.setText(QtGui.QApplication.translate("ObjectExplorer", "sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_moduleobject.setText(QtGui.QApplication.translate("ObjectExplorer", "moduleobject", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_mainobject.setText(QtGui.QApplication.translate("ObjectExplorer", "mainobject", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_other.setText(QtGui.QApplication.translate("ObjectExplorer", "other", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(0, QtGui.QApplication.translate("ObjectExplorer", "Object/Index", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(1, QtGui.QApplication.translate("ObjectExplorer", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(2, QtGui.QApplication.translate("ObjectExplorer", "Category", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(3, QtGui.QApplication.translate("ObjectExplorer", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidget.headerItem().setText(4, QtGui.QApplication.translate("ObjectExplorer", "Contents", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_rootObject.setText(QtGui.QApplication.translate("ObjectExplorer", "my_namespace", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("ObjectExplorer", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("ObjectExplorer", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy_path.setText(QtGui.QApplication.translate("ObjectExplorer", "Copy path", None, QtGui.QApplication.UnicodeUTF8))

